#ifndef CASCOREBUSINESS_GLOBAL_H
#define CASCOREBUSINESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASCOREBUSINESS_LIBRARY)
#  define CASCOREBUSINESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASCOREBUSINESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASCOREBUSINESS_GLOBAL_H
