#ifndef CASCOREDATA_GLOBAL_H
#define CASCOREDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASCOREDATA_LIBRARY)
#  define CASCOREDATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASCOREDATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASCOREDATA_GLOBAL_H
